# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [5]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

In [6]:
# print api key to ensure correct
g_key

'AIzaSyCkdwSeOcjszNhV_1lJn0zkuihzAWtmRHs'

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [10]:
# Reference the file where the CSV is located
weather_path = "../instructions/output_data/cities.csv"

# Import the data into a Pandas DataFrame
weather_data = pd.read_csv(weather_path)
weather_data.head()

,Unnamed: 0,City,Country,Cloudiness,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,Shache,CN,98,97,38.42,77.24,0.56,0.63
1,1,Ushuaia,AR,72,96,-54.80,-68.30,1.88,2.66
2,2,Hilo,US,90,65,19.73,-155.09,25.00,1.50
3,3,Khatanga,RU,57,98,71.97,102.50,-29.85,1.36
4,4,Punta Arenas,CL,20,70,-53.15,-70.92,9.00,5.70

In [11]:
# Remove Unnamed column
weather_data = weather_data[["City","Country","Cloudiness","Humidity","Lat","Lng","Max Temp","Wind Speed"]]
weather_data.head()

,City,Country,Cloudiness,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Shache,CN,98,97,38.42,77.24,0.56,0.63
1,Ushuaia,AR,72,96,-54.80,-68.30,1.88,2.66
2,Hilo,US,90,65,19.73,-155.09,25.00,1.50
3,Khatanga,RU,57,98,71.97,102.50,-29.85,1.36
4,Punta Arenas,CL,20,70,-53.15,-70.92,9.00,5.70

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [12]:
# configure gmaps 
gmaps.configure(api_key=g_key)

In [13]:
# set coordinates
coordinates = weather_data[["Lat", "Lng"]].astype(float)

# convert the new DataFrame to a list that can be passed 
coordinates = coordinates.values.tolist()

Humidity_heatmap = weather_data["Humidity"].astype(float)

# Create a humidity Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(coordinates, weights=Humidity_heatmap, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

Narrow down the DataFrame to find your ideal weather condition. For example:

A max temperature lower than 80 degrees but higher than 70. Wind speed less than 10 mph. Zero cloudiness.

Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.
Feel free to adjust to your specifications but be sure to limit the number of rows returned by your API requests to a reasonable number.

In [14]:
# My conditions: Max temperature between 15 - 23 celsius, less than 10 % cloudiness

ideal_weather1 = weather_data.loc[weather_data["Max Temp"] > 15, :]
ideal_weather2 = ideal_weather1.loc[ideal_weather1["Max Temp"] < 23, :]
ideal_weather = ideal_weather2.loc[ideal_weather2["Cloudiness"] < 10, :]

ideal_weather

,City,Country,Cloudiness,Humidity,Lat,Lng,Max Temp,Wind Speed
62,Mar del Plata,AR,0,76,-38.00,-57.56,17.78,0.59
75,Lebu,CL,1,92,-37.62,-73.65,15.37,2.86
103,Guerrero Negro,MX,0,80,27.98,-114.06,15.96,2.00
118,Luderitz,NaN,0,82,-26.65,15.16,19.00,6.70
131,Constitucion,CL,0,68,-35.33,-72.42,17.38,1.55
144,Manga,BF,0,11,11.66,-1.07,19.44,4.51
180,Sindou,BF,8,11,10.67,-5.17,18.79,2.27
181,Blantyre,MW,3,80,-15.79,35.01,22.84,0.51
203,Treinta y Tres,UY,0,93,-33.23,-54.38,18.84,3.64
215,Dwarka,IN,0,72,22.24,68.97,22.58,3.68
232,Rocha,UY,0,77,-34.48,-54.33,15.32,2.03
262,Itupeva,BR,0,88,-23.15,-47.06,19.44,2.60
274,Wagar,SD,0,69,16.15,36.20,17.16,8.97
291,Mae Hong Son,TH,7,45,19.30,97.97,20.00,1.00
295,Celestun,MX,0,83,20.87,-90.40,21.88,9.73
323,Rawson,AR,0,52,-43.30,-65.10,19.96,13.34
343,Vallenar,CL,0,70,-28.57,-70.76,18.94,1.23
386,Walvis Bay,NaN,0,93,-22.96,14.51,17.22,2.60
392,Americana,BR,0,88,-22.74,-47.33,19.44,2.60
416,Chui,UY,1,82,-33.70,-53.46,17.99,1.31
473,Graaff-Reinet,ZA,1,83,-32.25,24.53,19.44,1.34
504,Santa Maria,BR,0,53,-29.68,-53.81,20.16,2.06
515,Larreynaga,NI,0,75,12.68,-86.57,21.08,1.79
516,Porto Murtinho,BR,0,54,-21.70,-57.88,21.91,0.97

In [ ]:


### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display Map